package org.millenaire.client;

import com.mojang.logging.LogUtils;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Optional;
import net.minecraft.SharedConstants;
import net.minecraft.network.chat.Component;
import net.minecraft.server.packs.PackLocationInfo;
import net.minecraft.server.packs.PackSelectionConfig;
import net.minecraft.server.packs.PackType;
import net.minecraft.server.packs.PathPackResources.PathResourcesSupplier;
import net.minecraft.server.packs.repository.Pack;
import net.minecraft.server.packs.repository.PackSource;
import net.minecraft.server.packs.repository.Pack.Position;
import net.neoforged.api.distmarker.Dist;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.fml.loading.FMLPaths;
import net.neoforged.neoforge.event.AddPackFindersEvent;
import org.millenaire.content.BuiltInCultures;
import org.millenaire.content.ContentDirectoryManager;
import org.millenaire.content.CustomContentIndex;
import org.millenaire.content.SubmodRoot;
import org.slf4j.Logger;

@EventBusSubscriber(modid = "millenaire", value = Dist.CLIENT)
public final class CustomContentPackFinder {
   private static final Logger LOGGER = LogUtils.getLogger();

   private CustomContentPackFinder() {
   }

   @SubscribeEvent
   public static void onAddPackFinders(AddPackFindersEvent event) {
      if (event.getPackType() == PackType.CLIENT_RESOURCES) {
         ContentDirectoryManager.initClient(FMLPaths.GAMEDIR.get());
         if (ContentDirectoryManager.isInitialized()) {
            CustomContentIndex index = CustomContentIndex.rebuild(BuiltInCultures.IDS);

            for (String culture : index.indexedCultures()) {
               for (SubmodRoot submod : index.rootsForCulture(culture)) {
                  registerPackForCulture(event, submod, culture);
               }
            }
         }
      }
   }

   private static void ensurePackMcmeta(Path rpDir, String packId) {
      Path metaPath = rpDir.resolve("pack.mcmeta");
      if (!Files.exists(metaPath)) {
         int packFormat = SharedConstants.getCurrentVersion().getPackVersion(PackType.CLIENT_RESOURCES);
         String json = "{\n  \"_comment\": \"Auto-generated by Millénaire — safe to delete; will be regenerated on boot.\",\n  \"pack\": {\n    \"description\": \"Millénaire custom-content pack: "
            + packId
            + "\",\n    \"pack_format\": "
            + packFormat
            + "\n  }\n}\n";

         try {
            Files.writeString(metaPath, json, StandardCharsets.UTF_8);
            LOGGER.info("Synthesized {} for custom-content resourcepack '{}'", metaPath, packId);
         } catch (IOException e) {
            LOGGER.warn("Could not synthesize {} for resourcepack '{}': {}", new Object[]{metaPath, packId, e.getMessage()});
         }
      }
   }

   private static void registerPackForCulture(AddPackFindersEvent event, SubmodRoot submod, String culture) {
      Path rpDir = submod.root().resolve("cultures").resolve(culture).resolve("resourcepack");
      if (Files.isDirectory(rpDir)) {
         String packId = "millenaire_custom_" + submod.name() + "_" + culture;
         Component displayName = Component.literal("Millénaire — " + submod.name() + " / " + culture);
         ensurePackMcmeta(rpDir, packId);
         event.addRepositorySource(
            consumer -> {
               Pack pack = Pack.readMetaAndCreate(
                  new PackLocationInfo(packId, displayName, PackSource.BUILT_IN, Optional.empty()),
                  new PathResourcesSupplier(rpDir),
                  PackType.CLIENT_RESOURCES,
                  new PackSelectionConfig(true, Position.TOP, false)
               );
               if (pack != null) {
                  consumer.accept(pack);
                  LOGGER.debug("Registered custom-content pack: {} ({})", packId, rpDir);
               } else {
                  LOGGER.warn("Could not read pack metadata at {} — skipping", rpDir);
               }
            }
         );
      }
   }
}
